Repository nxnaxx/hululug-server, pull requests merged in 2024-11, with the labels that each got.

#40 [FEAT] 라면 월드컵 이벤트 리스트 및 total_count 조회 API 추가
  src/app.module.ts
  src/modules/events/events.module.ts
  src/modules/events/schemas/index.ts
  src/modules/events/schemas/ramen.schema.ts
  src/modules/events/schemas/worldcup.schema.ts
  src/modules/events/services/index.ts
  src/modules/events/services/worldcup-list.service.ts
  src/modules/events/worldcup.controller.ts
  src/modules/users/index.ts
  src/modules/users/schemas/index.ts
  src/modules/users/schemas/user.schema.ts
  src/modules/users/services/signoff.service.ts
Labels: feature, API

#42 [FEAT] 라면 월드컵 이벤트 제품 정보 조회 API 추가
  src/modules/events/events.module.ts
  src/modules/events/services/index.ts
  src/modules/events/services/worldcup-ramen-info.service.ts
  src/modules/events/worldcup.controller.ts
  src/modules/users/services/signup.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: feature, API

#46 [FEAT] 상세 레시피 조회 API 구현
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, API

#48 [FEAT] [FEAT] 라면 월드컵 이벤트 최종 선택 라면 카운트 API 추가
  src/modules/events/events.module.ts
  src/modules/events/services/index.ts
  src/modules/events/services/worldcup-ramen-info.service.ts
  src/modules/events/services/worldcup-select.service.ts
  src/modules/events/worldcup.controller.ts
  src/modules/users/services/signoff.service.ts
  src/modules/users/services/signout.service.ts
  src/modules/users/services/update-user.service.ts
Labels: feature, API

#49 [FEAT] 레시피 삭제 API 구현
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, refactor, API

#52 [FEAT] 레시피 등록 API response 수정
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, API

#54 [FEAT] 댓글 등록 API 구현
  src/app.module.ts
  src/common/decorators/userId.decorator.ts
  src/modules/comments/.gitkeep
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.module.ts
  src/modules/comments/comments.repository.ts
  src/modules/comments/comments.service.ts
  src/modules/comments/dto/create-comment.dto.ts
  src/modules/comments/index.ts
  src/modules/comments/schema/comment.schema.ts
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.module.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, API

#57 [FEAT] 태그 리스트 조회 API 추가
  src/app.module.ts
  src/modules/aws/aws.service.ts
  src/modules/recipes/recipes.service.ts
  src/modules/tags/schemas/index.ts
  src/modules/tags/schemas/tag.schema.ts
  src/modules/tags/tags.controller.ts
  src/modules/tags/tags.module.ts
  src/modules/tags/tags.service.ts
  src/modules/users/services/signup.service.ts
  src/modules/users/services/update-user.service.ts
  src/modules/users/users.controller.ts
Labels: feature, API

#59 [FEAT] 댓글 조회 API 구현
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.repository.ts
  src/modules/comments/comments.service.ts
  src/modules/comments/dto/create-comment.dto.ts
  src/modules/comments/dto/get-comments.dto.ts
  src/modules/comments/dto/index.ts
  src/modules/comments/schema/comment.schema.ts
Labels: feature, API

#61 [FEAT] 북마크 레시피들의 프리뷰 정보 조회 API 추가
  src/modules/recipes/recipes.service.ts
  src/modules/users/services/bookmark.service.ts
  src/modules/users/services/index.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: feature, API

#63 [FEAT] 레시피 등록, 삭제 API와 userModel 연결
  src/modules/aws/aws.service.ts
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, performance, API

#67 [FEAT] 댓글 삭제 API 구현
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.repository.ts
  src/modules/comments/comments.service.ts
  src/modules/comments/dto/delete-comment.dto.ts
  src/modules/comments/dto/index.ts
  src/modules/comments/dto/update-comment.dto.ts
  src/modules/recipes/recipes.repository.ts
Labels: feature, API

#68 [FEAT] 나의 레시피 프리뷰 정보 조회 API 추가
  src/modules/users/services/index.ts
  src/modules/users/services/my-recipes.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: feature, API

#70 [FEAT] 나의 댓글 정보 조회 API 추가
  src/modules/comments/index.ts
  src/modules/users/services/bookmark.service.ts
  src/modules/users/services/index.ts
  src/modules/users/services/my-comments.service.ts
  src/modules/users/services/my-recipes.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: feature, API

#73 [FEAT] 레시피 좋아요 API 구현
  src/modules/comments/comments.controller.ts
  src/modules/recipes/dto/create-recipe.dto.ts
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, API

#74 [FEAT] 라면 월드컵 이벤트 API 변경
  src/modules/events/events.module.ts
  src/modules/events/interface/index.ts
  src/modules/events/interface/ramen.interface.ts
  src/modules/events/schemas/index.ts
  src/modules/events/schemas/ramen.schema.ts
  src/modules/events/schemas/worldcup.schema.ts
  src/modules/events/services/index.ts
  src/modules/events/services/worldcup-list.service.ts
  src/modules/events/services/worldcup-ramen-info.service.ts
  src/modules/events/services/worldcup-select.service.ts
  src/modules/events/worldcup.controller.ts
  src/modules/users/users.module.ts
Labels: feature, API

#76 [FEAT] 레시피 북마크 API 구현
  src/modules/recipes/dto/create-recipe.dto.ts
  src/modules/recipes/dto/index.ts
  src/modules/recipes/dto/toggle-recipe.dto.ts
  src/modules/recipes/recipes.controller.ts
  src/modules/recipes/recipes.repository.ts
  src/modules/recipes/recipes.service.ts
Labels: feature, API

#78 [FEAT] 전역 응답 인터셉터 수정
  src/common/interceptors/global-response.interceptor.ts
Labels: feature, API

#81 [FEAT] CloudFront 적용하여 성능 개선
  src/auth/test/auth.http
  src/auth/test/test.schema.ts
  src/config/configuration.ts
  src/modules/aws/aws.service.ts
  src/modules/comments/comments.controller.ts
  src/modules/events/.gitkeep
  src/modules/recipes/recipes.service.ts
  src/modules/users/.gitkeep
  tests/recipes.http
Labels: performance, refactor

#83 [CHORE] CORS 설정 추가
  src/main.ts
Labels: feature

#95 [FEAT] Swagger 일부 명세 추가
  package.json
  src/main.ts
  src/modules/comments/comments.controller.ts
  src/modules/comments/dto/create-comment.dto.ts
  src/modules/comments/dto/get-comments.dto.ts
  src/modules/comments/dto/update-comment.dto.ts
  src/modules/recipes/dto/create-recipe.dto.ts
  src/modules/recipes/dto/get-recipes.dto.ts
  src/modules/recipes/dto/res-recipes.dto.ts
  src/modules/recipes/dto/toggle-recipe.dto.ts
  src/modules/recipes/recipes.controller.ts
  yarn.lock
Labels: docs, feature

#98 [FEAT] Swagger 일부 명세 추가 2
  README.md
  src/modules/events/dto/get-worldcup-ramen.dto.ts
  src/modules/events/dto/index.ts
  src/modules/events/dto/select-ramen.dto.ts
  src/modules/events/worldcup.controller.ts
  src/modules/tags/dto/get-tags.dto.ts
  src/modules/tags/dto/index.ts
  src/modules/tags/tags.controller.ts
  src/modules/users/dtos/create-session.dto.ts
  src/modules/users/dtos/create-user.dto.ts
  src/modules/users/dtos/get-comments.dto.ts
  src/modules/users/dtos/get-kakao-url.dto.ts
  src/modules/users/dtos/get-recipe-preview.dto.ts
  src/modules/users/dtos/index.ts
  src/modules/users/dtos/update-user.dto.ts
  src/modules/users/users.controller.ts
Labels: docs, feature

#100 [FEAT] Swagger 일부 명세 추가 2
  src/modules/events/dto/get-worldcup-ramen.dto.ts
  src/modules/events/dto/index.ts
  src/modules/events/dto/select-ramen.dto.ts
  src/modules/events/worldcup.controller.ts
  src/modules/tags/dto/get-tags.dto.ts
  src/modules/tags/dto/index.ts
  src/modules/tags/tags.controller.ts
  src/modules/users/dtos/create-session.dto.ts
  src/modules/users/dtos/create-user.dto.ts
  src/modules/users/dtos/get-comments.dto.ts
  src/modules/users/dtos/get-kakao-url.dto.ts
  src/modules/users/dtos/get-recipe-preview.dto.ts
  src/modules/users/dtos/index.ts
  src/modules/users/dtos/update-user.dto.ts
  src/modules/users/users.controller.ts
Labels: docs, feature

#101 [FIX] Swagger 일부 명세 수정
  src/modules/users/dtos/create-user.dto.ts
  src/modules/users/dtos/update-user.dto.ts
Labels: bug, docs, feature
